name = "FishTank"
uuid = "b38b52d1-0eac-4161-8266-eab412337ac4"
authors = ["Jake W. Liu"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
